// <auto-generated />
using System;
using InsurancePremiumInquiry.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsurancePremiumInquiry.Infrastructure.Migrations
{
    [DbContext(typeof(InsurancePremiumInquiryContext))]
    partial class InsurancePremiumInquiryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsurancePremiumInquiry.Domain.Models.BenefitRequests.Aggregate.BenefitRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("BenefitRequests", (string)null);
                });

            modelBuilder.Entity("InsurancePremiumInquiry.Domain.Models.BenefitRequests.ValueObjects.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BenefitRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("BenefitType")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BenefitRequestId");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("InsurancePremiumInquiry.Domain.Models.BenefitRequests.ValueObjects.Benefit", b =>
                {
                    b.HasOne("InsurancePremiumInquiry.Domain.Models.BenefitRequests.Aggregate.BenefitRequest", "BenefitRequest")
                        .WithMany("Benefits")
                        .HasForeignKey("BenefitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenefitRequest");
                });

            modelBuilder.Entity("InsurancePremiumInquiry.Domain.Models.BenefitRequests.Aggregate.BenefitRequest", b =>
                {
                    b.Navigation("Benefits");
                });
#pragma warning restore 612, 618
        }
    }
}
